# Generated by Django 2.1.4 on 2018-12-25 06:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annotation', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=25)),
                ('description', models.TextField(max_length=100)),
                ('status', models.TextField(max_length=12)),
                ('actionable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('incident_id', models.TextField(max_length=20, unique=True)),
                ('triggered', models.DateTimeField()),
                ('urgency', models.TextField()),
                ('annotation', models.ForeignKey(on_delete=False, to='oncall.Annotations')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team', models.TextField()),
                ('schedule', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
